server:
  port: 8082

spring:
  application:
    name: cost-tracking-service
  config:
    import: "configserver:http://config-server:8888"
  cloud:
    config:
      retry:
        max-attempts: 10
        initial-interval: 3000
        max-interval: 10000
        multiplier: 1.5
      fail-fast: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true