server:
  port: 8081

spring:
  application:
    name: gateway-service
  config:
    import: "configserver:http://config-server:8888"
  cloud:
    config:
      retry:
        max-attempts: 10
        initial-interval: 3000
        max-interval: 10000
        multiplier: 1.5
      fail-fast: true
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true