# nginx/nginx.conf
events {}
http {
    upstream gateway_cluster {
        server gateway-1:8081;
        server gateway-2:8081;
        server gateway-3:8081;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://gateway_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}